'use strict';

const CURRICULUM = {
"5th":{
"Mathematics":["The Fish Tale","Shapes and Angles","How Many Squares","Parts and Wholes","Does it Look the Same","Be My Multiple I'll be Your Factor","Can You See the Pattern","Mapping Your Way","Boxes and Sketches","Tenths and Hundredths","Area and its Boundary","Smart Charts","Ways to Multiply and Divide","How Big How Heavy"],
"Science":["Super Senses","A Snake Charmer's Story","From Tasting to Digesting","Mangoes Round the Year","Seeds and Seeds","Every Drop Counts","Experiments with Water","Up You Go","Sunita in Space","A Shelter so High","When the Earth Shook","Who will do this Work","On the Move Again"],
"English":["Reading Comprehension","Nouns and Pronouns","Simple Tenses","Vocabulary Building","Writing: Short Paragraphs","Poem Appreciation"]
},
"6th":{
"Mathematics":["Knowing Our Numbers","Whole Numbers","Playing with Numbers","Basic Geometrical Ideas","Understanding Elementary Shapes","Integers","Fractions","Decimals","Data Handling","Mensuration","Algebra","Ratio and Proportion","Symmetry"],
"Science":["Food: Where Does It Come From","Components of Food","Fibre to Fabric","Sorting Materials into Groups","Separation of Substances","Changes Around Us","Getting to Know Plants","Body Movements","The Living Organisms and Their Surroundings","Motion and Measurement of Distances","Light Shadows and Reflections","Electricity and Circuits","Fun with Magnets","Water","Air Around Us"],
"English":["Reading Comprehension","Grammar Basics","Tenses","Vocabulary Building","Writing: Paragraphs","Poetry Appreciation"],
"Social Science":["What Where How and When","On the Trail of the Earliest People","Kinship Caste and Class","The Earth in the Solar System","Globe: Latitudes and Longitudes","Motions of the Earth","Diversity on Earth","India: Climate Vegetation and Wildlife","Understanding Diversity","Rural and Urban Livelihoods"]
},
"7th":{
"Mathematics":["Integers","Fractions and Decimals","Data Handling","Simple Equations","Lines and Angles","The Triangle and its Properties","Congruence of Triangles","Comparing Quantities","Rational Numbers","Practical Geometry","Perimeter and Area","Algebraic Expressions","Exponents and Powers","Symmetry","Visualising Solid Shapes"],
"Science":["Nutrition in Plants","Nutrition in Animals","Fibre to Fabric","Heat","Acids Bases and Salts","Physical and Chemical Changes","Weather Climate and Adaptations","Winds Storms and Cyclones","Soil","Respiration in Organisms","Transportation in Animals and Plants","Reproduction in Plants","Motion and Time","Electric Current and its Effects","Light","Forests: Our Lifeline"],
"English":["Reading Comprehension","Grammar: Clauses","Active and Passive Voice","Vocabulary Building","Writing: Letters","Poetry Appreciation"],
"Social Science":["Tracing Changes Through a Thousand Years","New Kings and Kingdoms","The Delhi Sultans","The Mughal Empire","Environment","Inside Our Earth","Our Changing Earth","Air","Water","Human Environment Interactions","On Equality","Role of the Government in Health","Understanding Media","Markets Around Us"]
},
"8th":{
"Mathematics":["Rational Numbers","Linear Equations in One Variable","Understanding Quadrilaterals","Practical Geometry","Data Handling","Squares and Square Roots","Cubes and Cube Roots","Comparing Quantities","Algebraic Expressions and Identities","Visualising Solid Shapes","Mensuration","Exponents and Powers","Direct and Inverse Proportions","Factorisation","Introduction to Graphs","Playing with Numbers"],
"Science":["Crop Production and Management","Microorganisms","Synthetic Fibres and Plastics","Materials: Metals and Non-Metals","Coal and Petroleum","Combustion and Flame","Conservation of Plants and Animals","Cell Structure and Functions","Reproduction in Animals","Reaching the Age of Adolescence","Force and Pressure","Friction","Sound","Chemical Effects of Electric Current","Some Natural Phenomena","Light","Pollution of Air and Water"],
"English":["Reading Comprehension","Grammar: Modals","Reported Speech","Vocabulary Building","Writing: Formal Letters","Poetry Appreciation"],
"Social Science":["How When and Where","From Trade to Territory","Ruling the Countryside","Tribals Dikus and the Vision of a Golden Age","The Making of the National Movement","India After Independence","Resources","Land Soil Water Natural Vegetation and Wildlife Resources","Mineral and Power Resources","Agriculture","Industries","The Indian Constitution","Understanding Secularism","Why Do We Need a Parliament","Law and Social Justice"]
},
"9th":{
"Mathematics":["Number Systems","Polynomials","Coordinate Geometry","Linear Equations in Two Variables","Introduction to Euclid's Geometry","Lines and Angles","Triangles","Quadrilaterals","Areas of Parallelograms and Triangles","Circles","Constructions","Heron's Formula","Surface Areas and Volumes","Statistics","Probability"],
"Science":["Matter in Our Surroundings","Is Matter Around Us Pure","Atoms and Molecules","Structure of the Atom","The Fundamental Unit of Life","Tissues","Diversity in Living Organisms","Motion","Force and Laws of Motion","Gravitation","Work and Energy","Sound","Why Do We Fall Ill","Natural Resources","Improvement in Food Resources"],
"English":["Reading Comprehension","Grammar: Determiners and Tenses","Editing and Omission","Vocabulary Building","Writing: Diary Entry and Story","Literature: Prose and Poetry Analysis"],
"Social Science":["The French Revolution","Socialism in Europe and the Russian Revolution","Nazism and the Rise of Hitler","Forest Society and Colonialism","Pastoralists in the Modern World","India Size and Location","Physical Features of India","Drainage","Climate","Natural Vegetation and Wildlife","Population","Democracy in the Contemporary World","Constitutional Design","Electoral Politics","Working of Institutions","Democratic Rights","The Story of Village Palampur","Poverty as a Challenge","Food Security in India"]
},
"10th":{
"Mathematics":["Real Numbers","Polynomials","Pair of Linear Equations in Two Variables","Quadratic Equations","Arithmetic Progressions","Triangles","Coordinate Geometry","Introduction to Trigonometry","Applications of Trigonometry","Circles","Areas Related to Circles","Surface Areas and Volumes","Statistics","Probability"],
"Science":["Chemical Reactions and Equations","Acids Bases and Salts","Metals and Non-metals","Carbon and its Compounds","Life Processes","Control and Coordination","How do Organisms Reproduce","Heredity and Evolution","Light Reflection and Refraction","The Human Eye and the Colourful World","Electricity","Magnetic Effects of Electric Current","Sources of Energy","Our Environment","Management of Natural Resources"],
"English":["Reading Comprehension","Grammar: Reported Speech and Modals","Vocabulary Building","Writing: Analytical Paragraph and Article","Literature: First Flight and Footprints Without Feet"],
"Social Science":["The Rise of Nationalism in Europe","Nationalism in India","The Making of a Global World","The Age of Industrialisation","Print Culture and the Modern World","Resources and Development","Forest and Wildlife Resources","Water Resources","Agriculture","Minerals and Energy Resources","Manufacturing Industries","Lifelines of National Economy","Power Sharing","Federalism","Democracy and Diversity","Gender Religion and Caste","Popular Struggles and Movements","Political Parties","Outcomes of Democracy","Sectors of the Indian Economy","Money and Credit","Globalisation and the Indian Economy","Consumer Rights"]
},
"11th":{
"Physics":["Physical World","Units and Measurements","Motion in a Straight Line","Motion in a Plane","Laws of Motion","Work Energy and Power","System of Particles and Rotational Motion","Gravitation","Mechanical Properties of Solids","Mechanical Properties of Fluids","Thermal Properties of Matter","Thermodynamics","Kinetic Theory","Oscillations","Waves"],
"Chemistry":["Some Basic Concepts of Chemistry","Structure of Atom","Classification of Elements and Periodicity","Chemical Bonding and Molecular Structure","States of Matter","Thermodynamics","Equilibrium","Redox Reactions","Hydrogen","The s-Block Elements","The p-Block Elements","Organic Chemistry Basic Principles","Hydrocarbons","Environmental Chemistry"],
"Biology":["The Living World","Biological Classification","Plant Kingdom","Animal Kingdom","Morphology of Flowering Plants","Anatomy of Flowering Plants","Structural Organisation in Animals","Cell: The Unit of Life","Biomolecules","Cell Cycle and Cell Division","Transport in Plants","Mineral Nutrition","Photosynthesis in Higher Plants","Respiration in Plants","Plant Growth and Development","Digestion and Absorption","Breathing and Exchange of Gases","Body Fluids and Circulation","Excretory Products and their Elimination","Locomotion and Movement","Neural Control and Coordination","Chemical Coordination and Integration"],
"Mathematics":["Sets","Relations and Functions","Trigonometric Functions","Complex Numbers","Linear Inequalities","Permutations and Combinations","Binomial Theorem","Sequences and Series","Straight Lines","Conic Sections","Introduction to Three Dimensional Geometry","Limits and Derivatives","Statistics","Probability"],
"Economics":["Introduction to Economics","Collection of Data","Organisation of Data","Presentation of Data","Measures of Central Tendency","Measures of Dispersion","Correlation","Index Numbers","Indian Economy on the Eve of Independence","Indian Economy 1950-1990","Liberalisation Privatisation and Globalisation"],
"Business Studies":["Business Trade and Commerce","Forms of Business Organisation","Private Public and Global Enterprises","Business Services","Emerging Modes of Business","Social Responsibility of Business","Formation of a Company","Sources of Business Finance","Small Business","Internal Trade","International Business"],
"Accountancy":["Introduction to Accounting","Theory Base of Accounting","Recording of Transactions","Bank Reconciliation Statement","Trial Balance and Rectification of Errors","Depreciation Provisions and Reserves","Bills of Exchange","Financial Statements"],
"English":["Reading Comprehension","Grammar and Vocabulary","Writing: Notice Letter and Article","Literature: Hornbill and Snapshots"]
},
"12th":{
"Physics":["Electric Charges and Fields","Electrostatic Potential and Capacitance","Current Electricity","Moving Charges and Magnetism","Magnetism and Matter","Electromagnetic Induction","Alternating Current","Electromagnetic Waves","Ray Optics and Optical Instruments","Wave Optics","Dual Nature of Radiation and Matter","Atoms","Nuclei","Semiconductor Electronics"],
"Chemistry":["Solutions","Electrochemistry","Chemical Kinetics","Surface Chemistry","General Principles of Isolation of Elements","The p-Block Elements","The d and f Block Elements","Coordination Compounds","Haloalkanes and Haloarenes","Alcohols Phenols and Ethers","Aldehydes Ketones and Carboxylic Acids","Amines","Biomolecules","Polymers","Chemistry in Everyday Life"],
"Biology":["Reproduction in Organisms","Sexual Reproduction in Flowering Plants","Human Reproduction","Reproductive Health","Principles of Inheritance and Variation","Molecular Basis of Inheritance","Evolution","Human Health and Disease","Microbes in Human Welfare","Biotechnology Principles and Processes","Biotechnology and its Applications","Organisms and Populations","Ecosystem","Biodiversity and Conservation"],
"Mathematics":["Relations and Functions","Inverse Trigonometric Functions","Matrices","Determinants","Continuity and Differentiability","Application of Derivatives","Integrals","Application of Integrals","Differential Equations","Vector Algebra","Three Dimensional Geometry","Linear Programming","Probability"],
"Economics":["Introduction to Microeconomics","Theory of Consumer Behaviour","Production and Costs","The Theory of the Firm Under Perfect Competition","Market Equilibrium","National Income Accounting","Money and Banking","Determination of Income and Employment","Government Budget and the Economy","Balance of Payments"],
"Business Studies":["Nature and Significance of Management","Principles of Management","Business Environment","Planning","Organising","Staffing","Directing","Controlling","Financial Management","Marketing Management","Consumer Protection"],
"Accountancy":["Accounting for Partnership Firms","Reconstitution of a Partnership Firm","Dissolution of Partnership Firm","Accounting for Share Capital","Issue and Redemption of Debentures","Financial Statements of a Company","Analysis of Financial Statements","Cash Flow Statement"],
"English":["Reading Comprehension","Grammar and Vocabulary","Writing: Report and Article","Literature: Flamingo and Vistas"]
}
};

module.exports = CURRICULUM;
