'use strict';

// Offline general-knowledge lookup ported from StudyMate 1.9.
const GENERAL_KNOWLEDGE = {
"capital of india":"New Delhi is the capital of India.",
"capital of maharashtra":"Mumbai is the capital of Maharashtra.",
"capital of usa":"Washington, D.C. is the capital of the United States.",
"capital of united states":"Washington, D.C. is the capital of the United States.",
"capital of uk":"London is the capital of the United Kingdom.",
"capital of france":"Paris is the capital of France.",
"capital of japan":"Tokyo is the capital of Japan.",
"capital of china":"Beijing is the capital of China.",
"capital of russia":"Moscow is the capital of Russia.",
"capital of australia":"Canberra is the capital of Australia (not Sydney, which is the largest city).",
"largest country":"Russia is the largest country in the world by area.",
"smallest country":"Vatican City is the smallest country in the world by area.",
"largest planet":"Jupiter is the largest planet in our solar system.",
"smallest planet":"Mercury is the smallest planet in our solar system.",
"closest planet to the sun":"Mercury is the closest planet to the Sun.",
"how many planets":"There are 8 planets in our solar system: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus and Neptune.",
"national animal of india":"The Bengal Tiger is the national animal of India.",
"national bird of india":"The Indian Peacock is the national bird of India.",
"national flower of india":"The Lotus is the national flower of India.",
"who is the prime minister of india":"You should check a current source for this, since it can change — I don't have live updates.",
"who is the president of india":"You should check a current source for this, since it can change — I don't have live updates.",
"longest river":"The Nile is generally considered the longest river in the world.",
"longest river in india":"The Ganga (Ganges) is the longest river in India.",
"tallest mountain":"Mount Everest is the tallest mountain above sea level.",
"tallest mountain in india":"Kangchenjunga is the tallest mountain located entirely in India.",
"first prime minister of india":"Jawaharlal Nehru was the first Prime Minister of India.",
"father of the nation india":"Mahatma Gandhi is known as the Father of the Nation in India.",
"when did india get independence":"India got independence on 15 August 1947.",
"when was india's constitution adopted":"India's Constitution was adopted on 26 November 1949 and came into effect on 26 January 1950.",
"speed of light":"The speed of light is about 300,000 kilometres per second (299,792 km/s).",
"boiling point of water":"Water boils at 100°C (212°F) at sea level.",
"freezing point of water":"Water freezes at 0°C (32°F).",
"how many bones in human body":"An adult human body has 206 bones.",
"how many teeth do humans have":"Adults typically have 32 teeth.",
"largest ocean":"The Pacific Ocean is the largest ocean in the world.",
"largest desert":"Antarctica is technically the largest desert; the largest hot desert is the Sahara.",
"who invented the telephone":"Alexander Graham Bell is credited with inventing the telephone.",
"who invented the light bulb":"Thomas Edison is widely credited with developing the practical incandescent light bulb.",
"who discovered gravity":"Sir Isaac Newton is credited with formulating the theory of gravity after observing a falling apple.",
"who wrote the national anthem of india":"Rabindranath Tagore wrote 'Jana Gana Mana', India's national anthem.",
"chemical symbol for water":"The chemical symbol/formula for water is H2O.",
"chemical symbol for gold":"The chemical symbol for gold is Au.",
"how many continents":"There are 7 continents: Asia, Africa, North America, South America, Antarctica, Europe and Australia.",
"how many oceans":"There are 5 oceans: Pacific, Atlantic, Indian, Southern and Arctic.",
"currency of india":"The currency of India is the Indian Rupee (₹).",
"currency of usa":"The currency of the United States is the US Dollar ($).",
"what is photosynthesis":"Photosynthesis is the process by which green plants use sunlight, water and carbon dioxide to make their own food (glucose) and release oxygen.",
"what is gravity":"Gravity is the force that pulls objects toward each other — it's what keeps us on the ground and keeps planets orbiting the sun."
};

module.exports = GENERAL_KNOWLEDGE;
